### ISSUE TITLE
ImportError: libjasper.so.1 when first testing

### ISSUE THREAD

**Issue by tvarty97** [riffnshred/nhl-led-scoreboard#113]
Followed the guide and everything was working fine (including the hello world test) up until the "Usage" section when you first test before setting it up to run on its own.

Logs:
:~/nhl-led-scoreboard $ sudo python3 src/main.py --led-gpio-mapping=adafruit-hat --led brightness=60 --led-slowdown-gpio=2
Traceback (most recent call last):
  File "src/main.py", line 12, in <module> from api.weather.ecWeather import ecWxWorker
  File "/home/pi/nhl-led-scoreboard/src/api/weather/ecWeather.py", line 1, in <module> from env_canada import ECData
  File "/usr/local/lib/python3.7/dist-packages/env_canada/__init__.py", line 2, in <module>from .ec_radar import *
  File "/usr/local/lib/python3.7/dist-packages/env_canada/ec_radar.py", line 9, in <module> import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 3, in <module> from .cv2 import *
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory

I'm using a Zero with the bonnet without the flicker mod and the most recent software (first attempt and downloaded a few days ago).

**Comment by riffnshred** [comment]
If got V1.2.1 (released last weekend) installed or do you got a previous version? Id suggest rerunning the install.sh and see if that fix it, otherwise a complet intall from scratch will definitly fix that.

**Comment by falkyre** [comment]
Oh man, looks like there was another env Canada library release. The guy that wrote it is using opencv it looks like.  @riffnshred I think the install.sh needs to force the env Canada version I have in the requirements.txt

**Comment by falkyre** [comment]
Quick fix

**Comment by falkyre** [comment]
sudo pip3 uninstall env-canada

**Comment by falkyre** [comment]
sudo pip3 install env-canada==0.0.35

**Comment by riffnshred** [comment]
Hah what the hell ??? Thanks I'll fix it and push an update later tonight.

**Comment by riffnshred** [comment]
This was fixed with v1.3.0
