### ISSUE TITLE
Scoreboard won't start on off day

### ISSUE THREAD

**Issue by jrakestraw** [riffnshred/nhl-led-scoreboard#190]
INFO: Validating config.json.....
INFO: config.json passes validation
No data for 20202021 Playoff
No default round for 20202021 Playoff.
2021-01-24 09:09:57 INFO NHL-LED-SCOREBOARD - v1.5.5 (64x32)
2021-01-24 09:10:00 INFO ['01/24 09:10', '\uf07b', 'Curr Cond N/A', '26.2F', '-13.5F', '67%', '16.9F']
2021-01-24 09:10:00 INFO ['40.3 mph', 'SSE', '\uf05b', '0.0 mph', '1026.0 MB', '▒\x82\x88', '14.9 mi']
2021-01-24 09:10:00 INFO Checking NWS weather alerts
2021-01-24 09:10:02 INFO Number of alerts is 0
2021-01-24 09:10:02 INFO No active NWS alerts in your area
2021-01-24 09:10:02 INFO Updating weather forecast every 1 hour(s) starting @ 10:00
2021-01-24 09:10:02 INFO Refreshing EC daily weather forecast
2021-01-24 09:10:02 INFO New forecast: [['Mon 01/25', 'Cloudy Periods', '▒\x80\x93', '-1F', '-2F'], ['Tue 01/26', 'Snow', '▒\x80\x9b', '1F', '-10F'], ['Wed 01/27', 'Mainly Sunny', '▒\x80\x8d', '-3F', '-8F']]
2021-01-24 09:10:02 INFO Forecast has changed and been updated....
2021-01-24 09:10:02 INFO [['Mon 01/25', 'Cloudy Periods', '▒\x80\x93', '-1F', '-2F'], ['Tue 01/26', 'Snow', '▒\x80\x9b', '1F', '-10F'], ['Wed 01/27', 'Mainly Sunny', '▒\x80\x8d', '-3F', '-8F']]
2021-01-24 09:10:02 INFO Weather forecast next update @ 10:00
2021-01-24 09:10:02 INFO Screen saver will start @ 22:00 and end @ 07:00
2021-01-24 09:10:02 INFO Rendering...
2021-01-24 09:10:02 INFO Your preferred teams are Off today
2021-01-24 09:10:02 INFO PING !!! Render off day
2021-01-24 09:10:02 INFO Checking for new day
2021-01-24 09:10:02 INFO It is not a new day
Traceback (most recent call last):
  File "src/main.py", line 139, in <module>
    run()
  File "src/main.py", line 134, in run
    MainRenderer(matrix, data, sleepEvent).render()
  File "/home/pi/nhl-led-scoreboard/src/renderer/main.py", line 69, in render
    self.__render_offday()
  File "/home/pi/nhl-led-scoreboard/src/renderer/main.py", line 94, in __render_offday
    self.boards._off_day(self.data, self.matrix,self.sleepEvent)
  File "/home/pi/nhl-led-scoreboard/src/boards/boards.py", line 81, in _off_day
    board(data, matrix,sleepEvent)
  File "/home/pi/nhl-led-scoreboard/src/boards/boards.py", line 222, in scoreticker
    Scoreticker(data, matrix, sleepEvent).render()
  File "/home/pi/nhl-led-scoreboard/src/boards/scoreticker.py", line 31, in render
    ScoreboardRenderer(self.data, self.matrix, Scoreboard(self.games[self.index], self.data)).render()
  File "/home/pi/nhl-led-scoreboard/src/renderer/scoreboard.py", line 24, in __init__
    'home'
  File "/home/pi/nhl-led-scoreboard/src/renderer/logos.py", line 24, in __init__
    self.load(team_abbrev)
  File "/home/pi/nhl-led-scoreboard/src/renderer/logos.py", line 42, in load
    self.logo = Image.open(filename)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/pi/nhl-led-scoreboard/assets/logos/CHI/light/64x32.png'

**Comment by riffnshred** [comment]
That is the same issue than issue #187 . I'm about to release a fix today.
