### ISSUE TITLE
Scoreboard will not load after updating to latest version

### ISSUE THREAD

**Issue by ingerson** [riffnshred/nhl-led-scoreboard#269]
I updated the scoreboard to the lastest version and the boards will not load.  The loading image displays and then after a bit the board goes blank and then the loading image comes back on.  I have tested the board with a few of the samples and they run as expected.  Below is the outpur when trying to start the scoreboard.

pi@scoreboard:~ $ cd nhl-led-scoreboard/
pi@scoreboard:~/nhl-led-scoreboard $ sudo python3 src/main.py --led-gpio-mapping=adafruit-hat --led-rows=32 --led-cols=64 --led-brightness=50 --led-slowdown-gpio=2
INFO: Validating config.json.....
INFO: config.json passes validation
Traceback (most recent call last):
```python 
 File "src/main.py", line 157, in <module>
    run()
  File "src/main.py", line 61, in run
    data = Data(config)
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 134, in __init__
    self.teams = self.get_teams()
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 240, in get_teams
    teams = nhl_api.teams()
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/__init__.py", line 23, in teams
    return [nhl_api.info.Info(x) for x in nhl_api.info.team_info()]
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/info.py", line 22, in team_info
    short_name = team['shortName']
KeyError: 'shortName'
```

**Comment by ingerson** [comment]
IAfter readin all of Issue 266, I feel that my issue is probably related to the possibly issue with the API.  Can
