### ISSUE TITLE
crash on boot

### ISSUE THREAD

**Issue by harmgsn** [riffnshred/nhl-led-scoreboard#270]
INFO: config.json passes validation
Traceback (most recent call last):
  File "src/main.py", line 157, in <module>
    run()
  File "src/main.py", line 61, in run
    data = Data(config)
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 134, in __init__
    self.teams = self.get_teams()
  File "/home/pi/nhl-led-scoreboard/src/data/data.py", line 240, in get_teams
    teams = nhl_api.teams()
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/__init__.py", line 23, in teams
    return [nhl_api.info.Info(x) for x in nhl_api.info.team_info()]
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/info.py", line 22, in team_info
    short_name = team['shortName']
KeyError: 'shortName'

This was running fine up until midnight tonight (new day -- friday was an off day, saturday is not).  Setting livemode = false and it still crashes

 nhl-led-scoreboard # cat VERSION
1.6.2

**Comment by harmgsn** [comment]
Riffnshred: @everyone Its has been reported that there is something going on with the API and the scoreboard might not run. I will investigate this later tonight

Nevermind.
