### ISSUE TITLE
Error with nhl-api-client (No matching distribution found) when installing 

### ISSUE THREAD

**Issue by ergoalkeeper** [riffnshred/nhl-led-scoreboard#437]
My scoreboard has been crashing (after starting it up for some time) and I was seeing a nhl_api_client error upon running:
`python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2`

```
pi@raspberrypi:~/nhl-led-scoreboard $ python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2
Traceback (most recent call last):
  File "src/main.py", line 5, in <module>
    from renderer.main import MainRenderer
  File "/home/pi/nhl-led-scoreboard/src/renderer/main.py", line 5, in <module>
    from boards.boards import Boards
  File "/home/pi/nhl-led-scoreboard/src/boards/boards.py", line 8, in <module>
    from boards.seriesticker import Seriesticker
  File "/home/pi/nhl-led-scoreboard/src/boards/seriesticker.py", line 6, in <module>
    from data.playoffs import Series
  File "/home/pi/nhl-led-scoreboard/src/data/playoffs.py", line 4, in <module>
    import nhl_api
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/__init__.py", line 1, in <module>
    import nhl_api.game
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/game.py", line 9, in <module>
    from nhl_api_client import Client
**ModuleNotFoundError: No module named 'nhl_api_client'**
```

So, I decided to run an update (followed up by trying a clean install) to remedy, but looks like the nhl-api-client issue still remains:

Message from the installer:
```
pi@raspberrypi:~/nhl-led-scoreboard $ ./scripts/install.sh
Installing required dependencies. This may take some time (10-20 minutes-ish)...
Running update
[OK] package build-essential
[OK] package git
[OK] package python3-setuptools
[OK] package python3-pip
[OK] package python3-dev
W: --force-yes is deprecated, use one of the options starting with --allow instead.
[NEW] package python3-pillow
[OK] package python3-numpy
[OK] package python3-gpiozero
[OK] package python3-cairosvg
[OK] package libatlas3-base
[OK] package libatlas-base-dev
[OK] package libraqm-dev
[OK] package jq
[OK] package pastebinit
[OK] package neofetch
[OK] package zsh
[OK] package dbus
🚨  ALL GOOD TO GO
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: env-canada==0.0.35 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (0.0.35)
Requirement already satisfied: ephem==3.7.7.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (3.7.7.0)
Requirement already satisfied: fastjsonschema>=2.14.4 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.14.4)
Requirement already satisfied: geocoder==1.38.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (1.38.1)
Collecting gpiozero==1.5.1 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/5a/06/e3440c452a0c2ba1f12527c12c5676b158f2591ac6c43979016f21f71b2a/gpiozero-1.5.1-py2.py3-none-any.whl
**Collecting nhl-api-client==1.0.4 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement nhl-api-client==1.0.4 (from -r requirements.txt (line 6)) (from versions: )
No matching distribution found for nhl-api-client==1.0.4 (from -r requirements.txt (line 6))**
```

Wasn't sure if others were experiencing this same issue or not, so wanted to create a bug report.
Running on a Raspberry Pi 3 with the Adafruit Hat w/ anti-Flicker mod
Raspbian 10 (buster) OS

**Comment by ergoalkeeper** [comment]
Just saw the note on the front page, closing
