### ISSUE TITLE
ephem module not installed

### ISSUE THREAD

**Issue by twfarley** [riffnshred/nhl-led-scoreboard#70]
First run through after an install and I got this error:

```
$ sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2
Traceback (most recent call last):
  File "src/main.py", line 9, in <module>
    from dimmer import Dimmer
  File "/home/pi/nhl-led-scoreboard/src/dimmer.py", line 1, in <module>
    import ephem
ModuleNotFoundError: No module named 'ephem'
```

I don't have a dimmer installed.

**Comment by twfarley** [comment]
Nevermind, I don't have pip3 installed.
